// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaERHWHwWzOvoG4Xk48kOoDbSAkA4qMY',
    appId: '1:387369171492:web:5fd57fe4981545314db6b1',
    messagingSenderId: '387369171492',
    projectId: 'vehicle-authentication-acc85',
    authDomain: 'vehicle-authentication-acc85.firebaseapp.com',
    storageBucket: 'vehicle-authentication-acc85.firebasestorage.app',
    measurementId: 'G-RGP9W50L85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsv3L-bFvAdbDgonSDtCIXSe2_5M3Lfxg',
    appId: '1:387369171492:android:5365ba44049566e54db6b1',
    messagingSenderId: '387369171492',
    projectId: 'vehicle-authentication-acc85',
    storageBucket: 'vehicle-authentication-acc85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRwEDiPUAlIM38-V9qTTZDXcOtiQ0XSZg',
    appId: '1:387369171492:ios:29118294d54b3bb24db6b1',
    messagingSenderId: '387369171492',
    projectId: 'vehicle-authentication-acc85',
    storageBucket: 'vehicle-authentication-acc85.firebasestorage.app',
    androidClientId: '387369171492-hbmrndmagver4bnva7ue6p4or53rag41.apps.googleusercontent.com',
    iosClientId: '387369171492-ecp15lfbacij07crl07t38uqaogja1k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRwEDiPUAlIM38-V9qTTZDXcOtiQ0XSZg',
    appId: '1:387369171492:ios:29118294d54b3bb24db6b1',
    messagingSenderId: '387369171492',
    projectId: 'vehicle-authentication-acc85',
    storageBucket: 'vehicle-authentication-acc85.firebasestorage.app',
    androidClientId: '387369171492-hbmrndmagver4bnva7ue6p4or53rag41.apps.googleusercontent.com',
    iosClientId: '387369171492-ecp15lfbacij07crl07t38uqaogja1k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRaERHWHwWzOvoG4Xk48kOoDbSAkA4qMY',
    appId: '1:387369171492:web:5fd57fe4981545314db6b1',
    messagingSenderId: '387369171492',
    projectId: 'vehicle-authentication-acc85',
    authDomain: 'vehicle-authentication-acc85.firebaseapp.com',
    storageBucket: 'vehicle-authentication-acc85.firebasestorage.app',
    measurementId: 'G-RGP9W50L85',
  );

}